Change Makefile.common to initial Prometheus common
Signed-off-by: bege13mot <bege13mot@gmail.com>

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -1,4 +1,4 @@
-# Copyright 2015 The Prometheus Authors
+# Copyright 2018 The Prometheus Authors
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
@@ -11,82 +11,79 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-GO     ?= GO15VENDOREXPERIMENT=1 go
-GOPATH := $(firstword $(subst :, ,$(shell $(GO) env GOPATH)))
-GOARCH := $(shell $(GO) env GOARCH)
-GOHOSTARCH := $(shell $(GO) env GOHOSTARCH)
 
-PROMTOOL    ?= $(GOPATH)/bin/promtool
-PROMU       ?= $(GOPATH)/bin/promu
-STATICCHECK ?= $(GOPATH)/bin/staticcheck
-pkgs         = $(shell $(GO) list ./... | grep -v /vendor/)
+# A common Makefile that includes rules to be reused in different prometheus projects.
+# !!! Open PRs only against the prometheus/prometheus/Makefile.common repository!
+
+# Example usage :
+# Create the main Makefile in the root project directory.
+# include Makefile.common
+# customTarget:
+# 	@echo ">> Running customTarget"
+#
+
+# Ensure GOBIN is not set during build so that promu is installed to the correct path
+unexport GOBIN
+
+GO           ?= go
+GOFMT        ?= $(GO)fmt
+FIRST_GOPATH := $(firstword $(subst :, ,$(shell $(GO) env GOPATH)))
+PROMU        := $(FIRST_GOPATH)/bin/promu
+STATICCHECK  := $(FIRST_GOPATH)/bin/staticcheck
+GOVENDOR     := $(FIRST_GOPATH)/bin/govendor
+pkgs          = ./...
 
 PREFIX                  ?= $(shell pwd)
 BIN_DIR                 ?= $(shell pwd)
-DOCKER_IMAGE_NAME       ?= node-exporter
 DOCKER_IMAGE_TAG        ?= $(subst /,-,$(shell git rev-parse --abbrev-ref HEAD))
-MACH                    ?= $(shell uname -m)
-DOCKERFILE              ?= Dockerfile
 
+all: style staticcheck unused build test
 
-ifeq ($(OS),Windows_NT)
-    OS_detected := Windows
-else
-    OS_detected := $(shell uname -s)
-endif
+style:
+	@echo ">> checking code style"
+	! $(GOFMT) -d $$(find . -path ./vendor -prune -o -name '*.go' -print) | grep '^'
 
-ifeq ($(GOHOSTARCH),amd64)
-	ifeq ($(OS_detected),$(filter $(OS_detected),Linux FreeBSD Darwin Windows))
-                # Only supported on amd64
-                test-flags := -race
-        endif
-endif
+check_license:
+	@echo ">> checking license header"
+	@licRes=$$(for file in $$(find . -type f -iname '*.go' ! -path './vendor/*') ; do \
+               awk 'NR<=3' $$file | grep -Eq "(Copyright|generated|GENERATED)" || echo $$file; \
+       done); \
+       if [ -n "$${licRes}" ]; then \
+               echo "license header checking failed:"; echo "$${licRes}"; \
+               exit 1; \
+       fi
 
-ifeq ($(OS_detected), Linux)
-    test-e2e := test-e2e
-else
-    test-e2e := skip-test-e2e
-endif
+format:
+	@echo ">> formatting code"
+	$(GO) fmt $(pkgs)
 
-ifeq ($(MACH), ppc64le)
-	e2e-out = collector/fixtures/e2e-ppc64le-output.txt
-else
-	e2e-out = collector/fixtures/e2e-output.txt
-endif
+vet:
+	@echo ">> vetting code"
+	$(GO) vet $(pkgs)
 
-# 64bit -> 32bit mapping for cross-checking. At least for amd64/386, the 64bit CPU can execute 32bit code but not the other way around, so we don't support cross-testing upwards.
-cross-test = skip-test-32bit
-define goarch_pair
-	ifeq ($$(OS_detected),Linux)
-		ifeq ($$(GOARCH),$1)
-			GOARCH_CROSS = $2
-			cross-test = test-32bit
-		endif
-	endif
-endef
+staticcheck: $(STATICCHECK)
+	@echo ">> running staticcheck"
+	$(STATICCHECK) -ignore "$(STATICCHECK_IGNORE)" $(pkgs)
 
-# By default, "cross" test with ourselves to cover unknown pairings.
-$(eval $(call goarch_pair,amd64,386))
-$(eval $(call goarch_pair,arm64,arm))
-$(eval $(call goarch_pair,mips64,mips))
-$(eval $(call goarch_pair,mips64el,mipsel))
+unused: $(GOVENDOR)
+	@echo ">> running check for unused packages"
+	@$(GOVENDOR) list +unused | grep . && exit 1 || echo 'No unused packages'
 
-all: style vet staticcheck checkmetrics build test $(cross-test) $(test-e2e)
+build: promu
+	@echo ">> building binaries"
+	$(PROMU) build --prefix $(PREFIX)
 
-$(GOPATH)/bin/promtool promtool:
-	@GOOS= GOARCH= $(GO) get -u github.com/prometheus/prometheus/cmd/promtool
+tarball: promu
+	@echo ">> building release tarball"
+	$(PROMU) tarball --prefix $(PREFIX) $(BIN_DIR)
 
-$(GOPATH)/bin/promu promu:
-	@GOOS= GOARCH= $(GO) get -u github.com/prometheus/promu
+promu:
+	GOOS= GOARCH= $(GO) get -u github.com/prometheus/promu
 
-$(GOPATH)/bin/staticcheck:
-	@GOOS= GOARCH= $(GO) get -u honnef.co/go/tools/cmd/staticcheck
+$(FIRST_GOPATH)/bin/staticcheck:
+	GOOS= GOARCH= $(GO) get -u honnef.co/go/tools/cmd/staticcheck
 
+$(FIRST_GOPATH)/bin/govendor:
+	GOOS= GOARCH= $(GO) get -u github.com/kardianos/govendor
 
-.PHONY: all style format build test test-e2e vet tarball docker promtool promu staticcheck checkmetrics
-
-# Declaring the binaries at their default locations as PHONY targets is a hack
-# to ensure the latest version is downloaded on every make execution.
-# If this is not desired, copy/symlink these binaries to a different path and
-# set the respective environment variables.
-.PHONY: $(GOPATH)/bin/promtool $(GOPATH)/bin/promu $(GOPATH)/bin/staticcheck
+.PHONY: all style check_license format build test vet assets tarball docker promu staticcheck $(FIRST_GOPATH)/bin/staticcheck govendor $(FIRST_GOPATH)/bin/govendor
